import Link from 'next/link'
import Head from 'next/head'

const Home = ()=>{
  return(
    <div>
      <Head>
        <title>home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href='/'>
        <a title='home'>首页</a>
      </Link>
      <br/>
      <Link href='/list'>
        <a title='list'>列表页</a>
      </Link>
      <img src="/vercel.svg" alt="d"/>
    </div>
  )
}
export default Home;